### PR TITLE
Add This pointer to member functions

### LINKED ISSUE #38: Fix member function signatures
All member functions in Ada require a first argument that passes the instance.
E.g. `void C::f()` becomes `procedure f (This : access C)`.

### PR DESCRIPTION
**Pull request by senier**
Closes #38

### CODE REVIEW

**Review by jklmnn — CHANGES_REQUESTED** [review]
https://github.com/Componolit/capdpa/blob/aa150f7ff4d1739811c8abfa5506e8c8cff3c5b0/capdpa/cxx.py#L169 already adds the `This` argument to the IR (we didn't explicitly address this issue when I implemented this so this should be the only occurence). I suggest to remove that part since it is inconsistent with this version (and the output will probably just broken).

**Comment by senier** [comment]
Good catch, I removed this leftover.

**Review by jklmnn — CHANGES_REQUESTED** [review]
We should also adapt the function pointer to this scheme at https://github.com/Componolit/capdpa/blob/5bed6aa1614e9143e8a744d339f52d610de6e559/capdpa/IR/ir_function.py#L79. The static attribute is also used. `static` should be true for function pointers generated from a `MEMBERPOINTER` and false for anything else (`MEMBERPOINTER` explicitly states that the function is a member of a class and requires the first argument to be the class instance while anything else is not a class member and therefore doesn't require a class instance).

**Comment by senier** [comment]
Are you sure the above statement is correct? `static` functions do *not* get a pointer to a class instance as the first parameter, while you state that `static` should be true for `MEMBERPOINTER`s because it requires a class pointer. I would have expected the opposite...

**Comment by jklmnn** [comment]
Yes of course, you are right. `static` should be false on a `MEMBERPOINTER` since we always have a this argument.

**Review by jklmnn — APPROVED** [review]

**Pull request closed without merging**
